# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "foodics" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "foodics_password" } %>

development:
  <<: *default
  database: foodics_development

test:
  <<: *default
  database: foodics_test

production:
  <<: *default
  database: foodics_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
