# PostgreSQL configuration
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "foodics" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "foodics_password" } %>

development:
  <<: *default
  database: foodics_development

test:
  <<: *default
  database: foodics_test

production:
  primary:
    <<: *default
    database: foodics_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
  cache:
    <<: *default
    database: foodics_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: foodics_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: foodics_production_cable
    migrations_paths: db/cable_migrate
